# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.

imgsensor_isp6s-objs += \
	$(subdrv-rpath)/wl2868/wl2868.o \
	$(subdrv-rpath)/imgsensor_cfg_table.o \
	$(subdrv-rpath)/regulator/regulator.o \
	$(subdrv-rpath)/gpio/gpio.o \
	$(subdrv-rpath)/mclk/mclk.o